version: 1.0.{build}
shallow_clone: true
install:
- ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- dnvm install 1.0.0-beta6
- dnu restore --quiet --parallel
build:
  project: AppveyorAspNet5Build.sln
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
environment:
  DNX_BUILD_VERSION: beta6-%APPVEYOR_BUILD_NUMBER%
#init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
